title: Blog of Litchi Pi
email: litchi.pi@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
    The blog of a young dumb Rust and Python programmer, interested in
    a lot of different subjects and willing to talk about his discoveries.
baseurl: "/"
domain: "litchipi.github.io"
url: "https://litchipi.github.io"
author:
    name: "Litchi pi"
    email: "litchi.pi@protonmail.com"
    github: "https://github.com/litchipi/"
    twitter: "https://twitter.com/LitchiPi"
twitter_username: LitchiPi
github_username:  litchipi

# Build settings
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed

exclude:
    - _posts/2021-09-13-helloworld*
    - _posts/2021-09-13-test*

#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
